# Permalinks
permalink:        pretty

# Setup
title:            Collaborative Disagreement
tagline:          What, a tagline?
description:      >-
  Stray thoughts about who we are,
  how to relate to each other,
  and how to think more clearly.
baseurl:          /frog/

author:
  name:           Jesse Anderton
  email:          jessder@pm.me

paginate:         5

# Custom vars
version:          0.1.0
